#faces do dado#
print("as 6 faces do dado")
numero1 = ("#######\n#     #\n#  *  #\n#     #\n#######")
numero2 = ("#######\n#*    #\n#     #\n#    *#\n#######")
numero3 = ("#######\n#*    #\n#  *  #\n#    *#\n#######")
numero4 = ("#######\n# * * #\n#     #\n# * * #\n#######")
numero5 = ("#######\n# * * #\n#  *  #\n# * * #\n#######")
numero6 = ("#######\n# * * #\n# * * #\n# * * #\n#######")
print(numero1)
print(numero2)
print(numero3)
print(numero4)
print(numero5)
print(numero6)